export default [
  {
    matpel: "B Inggris",
    kelas: "Xi",
    Deskripsi: "Belajar Bahasa Inggris",
    file: "primary",
  },
  {
    matpel: "B Indonesia",
    kelas: "Xi",
    Deskripsi: "Belajar Bahasa indonesia",
    file: "primary",
  },
  {
    matpel: "PKN",
    kelas: "X",
    Deskripsi: "Belajar mengenai sejarah",
    file: "primary",
  },
  {
    matpel: "B Arab",
    kelas: "X",
    Deskripsi: "Praktikum Bahasa Arab",
    file: "primary",
  },
  {
    matpel: "B Inggris",
    kelas: "Xi",
    Deskripsi: "Belajar Bahasa Inggris",
    file: "primary",
  },
  {
    matpel: "B Indonesia",
    kelas: "Xi",
    Deskripsi: "Belajar Bahasa indonesia",
    file: "primary",
  },
  {
    matpel: "PKN",
    kelas: "X",
    Deskripsi: "Belajar mengenai sejarah",
    file: "primary",
  },
  {
    matpel: "B Arab",
    kelas: "X",
    Deskripsi: "Praktikum Bahasa Arab",
    file: "primary",
  },
  {
    matpel: "B Inggris",
    kelas: "Xi",
    Deskripsi: "Belajar Bahasa Inggris",
    file: "primary",
  },
  {
    matpel: "B Indonesia",
    kelas: "Xi",
    Deskripsi: "Belajar Bahasa indonesia",
    file: "primary",
  },
  {
    matpel: "PKN",
    kelas: "X",
    Deskripsi: "Belajar mengenai sejarah",
    file: "primary",
  },
  {
    matpel: "B Arab",
    kelas: "X",
    Deskripsi: "Praktikum Bahasa Arab",
    file: "primary",
  },
  {
    matpel: "B Inggris",
    kelas: "Xi",
    Deskripsi: "Belajar Bahasa Inggris",
    file: "primary",
  },
  {
    matpel: "B Inggris",
    kelas: "X",
    Deskripsi: "Belajar Bahasa Inggris",
    file: "primary",
  },
  {
    matpel: "B Inggris",
    kelas: "Xi",
    Deskripsi: "Belajar Bahasa Inggris",
    file: "primary",
  },
  {
    matpel: "B Inggris",
    kelas: "X",
    Deskripsi: "Belajar Bahasa Inggris",
    file: "primary",
  },
  {
    matpel: "B Inggris",
    kelas: "Xi",
    Deskripsi: "Belajar Bahasa Inggris",
    file: "primary",
  },
  {
    matpel: "B Inggris",
    kelas: "Xi",
    Deskripsi: "Belajar Bahasa Inggris",
    file: "primary",
  },
];
